version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: zen_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zen_mgt
      MYSQL_USER: zenadmin
      MYSQL_PASSWORD: zenadmin123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0
    container_name: zen_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: 