server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: zen-mgt-backend
  datasource:
    url: jdbc:mysql://localhost:3306/zen_mgt?useSSL=false&allowPublicKeyRetrieval=true
    username: zenadmin
    password: zenadmin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: localhost
      port: 6379
      password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    oauth2:
      enabled: false  # Toggle OAuth2 authentication
      client:
        registration:
          google:
            client-id: your-google-client-id
            client-secret: your-google-client-secret
            scope:
              - email
              - profile
            redirect-uri: http://localhost:8080/login/oauth2/code/google

logging:
  level:
    root: INFO
    com.zenmgt: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO

# Custom Application Properties
app:
  # Authentication Configuration
  auth:
    password-auth-enabled: true  # Toggle username/password authentication
    default-auth-method: password  # Options: password, oauth2
  jwt:
    secret-key: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds
    refresh-token:
      expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days in milliseconds

  # Snowflake ID Generator Configuration
  snowflake:
    worker-id: 1
    datacenter-id: 1

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    docExpansion: none
    disable-swagger-default-url: true
    config-url: /api/v3/api-docs/swagger-config
    url: /api/v3/api-docs
  show-actuator: false
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  writer-with-default-pretty-printer: true 